name: Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Install dependencies
        run: npm ci

      - name: Build Svelte app
        run: npm run build && mkdir -p build && cp -r .svelte-kit/output build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Debug - Check build output
        run: ls -l

      - name: Upload coverage report artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@main
        with:
          name: github-pages
  
      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/deploy-pages@v4
        env:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        with: 
          artifact_name: github-pages
          token: ${{ github.token }}
          preview: true
